# Generated by Django 5.0.3 on 2024-03-26 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('expertises', models.TextField()),
                ('outils_et_connaissances', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField()),
                ('type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('domaines', models.TextField()),
                ('outils_et_connaissances', models.TextField()),
                ('organisme', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('annee', models.IntegerField(default=2024)),
                ('palier', models.CharField(max_length=100)),
                ('domaine', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('preferences', models.TextField()),
                ('outils_et_connaissances', models.TextField()),
                ('encadreur_favoris', models.ManyToManyField(to='Platform.encadreur')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='Platform.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Platform.encadreur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Platform.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Platform.chat')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.chat')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.message')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_message', to='Platform.notification')),
            ],
        ),
        migrations.CreateModel(
            name='PropositionSujet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encadreur', models.ManyToManyField(related_name='sujet_propose', to='Platform.encadreur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujet_propose', to='Platform.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSujetAccepte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sujet_accepte', to='Platform.notification')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.propositionsujet')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPropositionSujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_proposition_sujet', to='Platform.notification')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.propositionsujet')),
            ],
        ),
        migrations.CreateModel(
            name='SujetEncadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.BooleanField()),
                ('palier', models.CharField(max_length=100)),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujet_publie', to='Platform.encadreur')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sujet_encadreur', to='Platform.sujet')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSujetAffecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sujet_affecte', to='Platform.notification')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.sujetencadreur')),
            ],
        ),
        migrations.CreateModel(
            name='SujetEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujet_cree', to='Platform.etudiant')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sujet_etudiant', to='Platform.sujet')),
            ],
        ),
        migrations.AddField(
            model_name='propositionsujet',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_envoye', to='Platform.sujetetudiant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='Platform.utilisateur'),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadreur', to='Platform.utilisateur'),
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrateur', to='Platform.utilisateur')),
            ],
        ),
    ]
