# Generated by Django 5.0.3 on 2024-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encadreur',
            old_name='nom',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='nom',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='type',
            new_name='child_type',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='organisme',
        ),
        migrations.AddField(
            model_name='sujet',
            name='child_type',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(default='user@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sujet',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
