# Generated by Django 5.0.3 on 2024-04-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0002_rename_nom_encadreur_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='destination',
            new_name='destinataire',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='lue',
            new_name='lu',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='PFE',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PFE', to='Platform.sujet'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='liste_de_choix',
            field=models.ManyToManyField(related_name='liste_de_choix', to='Platform.sujetencadreur'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='sujet_favoris',
            field=models.ManyToManyField(related_name='sujet_favoris', to='Platform.sujetencadreur'),
        ),
    ]
