# Generated by Django 5.0.3 on 2024-04-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0003_rename_destination_notification_destinataire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='child_type',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='id',
            new_name='_id',
        ),
        migrations.CreateModel(
            name='NotificationDelai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai', models.DateTimeField()),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delai', to='Platform.notification')),
            ],
        ),
    ]
