# Generated by Django 5.0.3 on 2024-04-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0004_rename_type_notification_child_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='_id',
            new_name='database_id',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='email',
            new_name='user_id',
        ),
    ]
