# Generated by Django 5.0.3 on 2024-05-05 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0006_etudiant_search_sujet_here'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='nom',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='PFE',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PFE', to='Platform.sujetencadreur'),
        ),
    ]
