# Generated by Django 5.0.3 on 2024-05-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0007_rename_nom_administrateur_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpropositionsujet',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='notificationpropositionsujet',
            name='proposition',
        ),
        migrations.RemoveField(
            model_name='notificationsujetaccepte',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='notificationsujetaccepte',
            name='proposition',
        ),
        migrations.RemoveField(
            model_name='propositionsujet',
            name='encadreur',
        ),
        migrations.RemoveField(
            model_name='propositionsujet',
            name='etudiant',
        ),
        migrations.RemoveField(
            model_name='propositionsujet',
            name='sujet',
        ),
        migrations.RemoveField(
            model_name='sujetetudiant',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='sujetencadreur',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='sujetetudiant',
            name='etudiant',
        ),
        migrations.RenameField(
            model_name='sujetencadreur',
            old_name='etat',
            new_name='disponible',
        ),
        migrations.AddField(
            model_name='sujetencadreur',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sujetencadreur',
            name='domaines',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sujetencadreur',
            name='outils_et_connaissances',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sujetencadreur',
            name='titre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sujetencadreur',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='PFE',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='Platform.sujetencadreur'),
        ),
        migrations.AlterField(
            model_name='sujetencadreur',
            name='encadreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujet_publie', to='Platform.encadreur'),
        ),
        migrations.AlterField(
            model_name='sujetencadreur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TEncadreur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('domaine', models.TextField()),
                ('outils', models.TextField()),
                ('child_type', models.PositiveSmallIntegerField()),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadreurt', to='Platform.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='TEncadreurExterne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entreprise', models.CharField(max_length=100)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadreur_externe', to='Platform.encadreur')),
            ],
        ),
        migrations.CreateModel(
            name='TEncadreurInterne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadreur_interne', to='Platform.encadreur')),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationMessage',
        ),
        migrations.DeleteModel(
            name='NotificationPropositionSujet',
        ),
        migrations.DeleteModel(
            name='NotificationSujetAccepte',
        ),
        migrations.DeleteModel(
            name='PropositionSujet',
        ),
        migrations.DeleteModel(
            name='Sujet',
        ),
        migrations.DeleteModel(
            name='SujetEtudiant',
        ),
    ]
