# Generated by Django 5.0.3 on 2024-05-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0008_remove_notificationpropositionsujet_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetencadreur',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sujetencadreur',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sujetencadreur',
            name='domaines',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sujetencadreur',
            name='encadreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujet_publie', to='Platform.tencadreur'),
        ),
        migrations.AlterField(
            model_name='sujetencadreur',
            name='outils_et_connaissances',
            field=models.TextField(default=''),
        ),
    ]
