# Generated by Django 5.0.3 on 2024-05-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0009_alter_sujetencadreur_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujetencadreur',
            name='encadreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujet_publie', to='Platform.encadreur'),
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='expertises',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='outils_et_connaissances',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='specialite',
        ),
        migrations.AddField(
            model_name='encadreur',
            name='child_type',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='domaines',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='outils',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TEncadreur',
        ),
    ]
