# Generated by Django 5.0.3 on 2024-05-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0010_alter_sujetencadreur_encadreur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TEncadreurExterne',
            new_name='EncadreurExterne',
        ),
        migrations.RenameModel(
            old_name='TEncadreurInterne',
            new_name='EncadreurInterne',
        ),
    ]
