# Generated by Django 5.0.3 on 2024-05-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0011_rename_tencadreurexterne_encadreurexterne_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='liste_de_choix',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='PFE',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='sujet_favoris',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='domaines',
        ),
        migrations.RemoveField(
            model_name='encadreur',
            name='type',
        ),
        migrations.RemoveField(
            model_name='encadreurexterne',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='encadreur_favoris',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='palier',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='search_sujet_here',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='password',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_id',
        ),
        migrations.AddField(
            model_name='administrateur',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrateur',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='bureau',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='expertises',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='encadreur',
            name='moyen_contact',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='nombre_binome_max',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreur',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreurexterne',
            name='poste',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encadreurexterne',
            name='societe',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('annee', models.IntegerField(default=2024)),
                ('palier', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('encadreur_favoris', models.ManyToManyField(to='Platform.encadreur')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='Platform.groupe'),
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('domaines', models.TextField(default='')),
                ('outils_et_connaissances', models.TextField(default='')),
                ('disponible', models.BooleanField(default=True)),
                ('palier', models.CharField(max_length=100)),
                ('liste_specialites', models.TextField(default='')),
                ('visible', models.BooleanField(default=True)),
                ('encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujet_publie', to='Platform.encadreur')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='PFE',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupe', to='Platform.sujet'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='liste_choix',
            field=models.ManyToManyField(related_name='groupe_liste_choix', to='Platform.sujet'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='sujet_favoris',
            field=models.ManyToManyField(related_name='groupe_favoris', to='Platform.sujet'),
        ),
        migrations.AlterField(
            model_name='notificationsujetaffecte',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.sujet'),
        ),
        migrations.DeleteModel(
            name='SujetEncadreur',
        ),
    ]
