# Generated by Django 5.0.3 on 2024-05-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0013_remove_message_chat_remove_message_auteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='liste_choix',
        ),
        migrations.AddField(
            model_name='notificationdelai',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_choix', to='Platform.groupe')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupe_liste_choix', to='Platform.sujet')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_general', to='Platform.notification')),
            ],
        ),
    ]
