# Generated by Django 5.0.3 on 2024-05-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0014_competence_domaine_specialite_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competence',
        ),
        migrations.DeleteModel(
            name='Domaine',
        ),
        migrations.DeleteModel(
            name='Specialite',
        ),
    ]
