# Generated by Django 5.0.3 on 2024-05-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0016_competence_domaine_specialite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujet',
            name='disponible',
        ),
    ]
