# Generated by Django 5.0.3 on 2024-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0017_remove_sujet_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='palier',
            field=models.CharField(default='L3', max_length=100),
            preserve_default=False,
        ),
    ]
