# Generated by Django 4.2.7 on 2024-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0018_specialite_palier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encadreur',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='encadreur',
            name='username',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='encadreurexterne',
            name='societe',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='encadreurinterne',
            name='grade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='encadreurinterne',
            name='specialite',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='username',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='palier',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sujet',
            name='titre',
            field=models.CharField(max_length=300),
        ),
    ]
